CREATE TABLE payment_orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number    VARCHAR(64)  NOT NULL UNIQUE,
    alfa_order_id   VARCHAR(64),
    client_user_id  BIGINT       NOT NULL REFERENCES users(id),
    paid_service_id BIGINT       NOT NULL REFERENCES paid_service(id),
    contact_phone   VARCHAR(25),
    notes           TEXT,
    preferred_date  DATE,
    preferred_time  TIME,
    amount_kopecks  BIGINT       NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paid_at         TIMESTAMP
);

CREATE INDEX idx_payment_orders_alfa_order_id  ON payment_orders(alfa_order_id);
CREATE INDEX idx_payment_orders_client_user_id ON payment_orders(client_user_id);
